FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine As build-env
WORKDIR /aspnetcore-mvc-docker

COPY . ./
RUN dotnet restore aspnetcore-mvc-docker.csproj
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine
WORKDIR /aspnetcore-mvc-docker
EXPOSE 80

COPY --from=build-env aspnetcore-mvc-docker/out ./
ENTRYPOINT [ "dotnet", "aspnetcore-mvc-docker.dll" ]